### ISSUE TITLE
[Feature] Cache existing replays to improve incremental performance

### ISSUE THREAD

**Issue by bclymer** [BrodyVoth/slippi-cumulative-stats#3]
## Idea

Implement a game-based cache so that future loads of the same game file will be significantly faster.

## Notes

An idea for an implementation is a JSON file that is a mapping of a hash (computed from the file name and some metadata) and all of the `data` returned by the computation task.

When loading a new game, first check if the hash of that game exists in the cache and use that value if found.

After done processing all the games, merge any new replays into the current JSON file and write that out.

Also it would be a good idea to create a `schema_version` argument as a top level property in the JSON file. If something changes with the structure of the `data`, the `schema_version` would be incremented and the cache would be invalidated.

**Comment by bclymer** [comment]
I plan on picking this up

**Comment by brandoncollins92** [comment]
Does it make sense to include the `slippi-cumulative-stats` release version in there as well? Then the code could chose whether to, for example, invalidate the cache across minor version or major version changes. Even if you don't plan on actually doing that kind invalidation from the start, it's better to include it in the cache file from the beginning.

**Comment by bclymer** [comment]
Yeah that's a good idea. Our data is pretty abstracted from the Slippi version (it's just a bunch of number) but at the same time it's really hard to know what Slippi might break. Worth adding considering the Slippi version won't update too often.

**Comment by BrodyVoth** [comment]
I think this is a great idea because the slow and redundant processing scares off repeat scans. Adding a slippi-cumulative-stats version makes sense to me as well in case of changes we make or the slippi-js dependency makes. Though, we should probably save everything that could be considered useful. Is it worth saving stuff like platform, ports, and colors just in case?

**Comment by BrodyVoth** [comment]
This has been implemented and released in 2.0.0. Thanks!
