### ISSUE TITLE
99+ hours is displayed as 10 hours

### ISSUE THREAD

**Issue by SpaceCowboy3514** [BrodyVoth/slippi-cumulative-stats#9]
![image](https://user-images.githubusercontent.com/57578722/105866113-a070b580-5fc1-11eb-9575-ac0fce5bf15f.png)

**Comment by BrodyVoth** [comment]
Can you confirm this happens on [2.2.0](https://github.com/BrodyVoth/slippi-cumulative-stats/releases/tag/2.2.0)?

**Comment by SpaceCowboy3514** [comment]
sorry lol I thought I had the most recent version

**Comment by BrodyVoth** [comment]
No worries.
